apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: remitmortgage-backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  rules:
    - host: api.remitmortgage.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: remitmortgage-backend
                port:
                  number: 80
